# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./tools
# Target is a library:  
HEADERS +=         tokenizer.h 

headers.files = $$HEADERS
headers.path = "$$(NMRDEV_DIR)/include/nmrdev"
message( $$(NMRDEV_DIR) )
INSTALLS += headers 
 
